### ISSUE TITLE
Paddles do not work on 6.2.1 for Retron77

### ISSUE THREAD

**Issue by Schvenn** [DirtyHairy/r77-firmware-ng#3]
Only the fire button works, the paddles do not control direction, at all.
Others are having the same issue:

https://atariage.com/forums/topic/287086-the-retron-77-and-using-paddles/?tab=comments#comment-4197206

**Comment by thrust26** [comment]
Thanks, I created an issue here: https://github.com/stella-emu/stella/issues/692

**Comment by thrust26** [comment]
I have fixed the problem. 

For now, a workaround is to use the "Advanced Settings" and default the input..

**Comment by Schvenn** [comment]
Setting the defaults does not work. For those of us with this issue, the paddle control is not recognized, at all; only the trigger button is. No amount of changes to the settings will fix that.

**Comment by thrust26** [comment]
Thanks, I will look into this again before we post a fix. Until then you have to map manually. 

The problem is that front ports of the R77 use axis Z and 3 for the paddles instead of the normal X and Y. So we initially try to map X and Z to one paddle and Y and 3 to the other one. The bug was, that only the first axis was mapped.
